import type { ExtractedVariant, SafetyFlags } from "./types";

const HIGH_RISK_GENES = new Set([
  "BRCA1", "BRCA2", "MLH1", "MSH2", "MSH6", "PMS2", "EPCAM",
  "PALB2", "ATM", "CHEK2", "TP53", "STK11", "CDH1", "MUTYH",
]);

export const MAIN_DISCLAIMER =
  "This document was generated by GeneTranslate and is intended for educational purposes only. It does not constitute medical advice. Please review all information with your genetic counselor or physician.";

export const HIGH_RISK_BANNER_TEXT =
  "This report includes findings in genes associated with hereditary cancer syndromes. These results can have significant implications for you and your family members. We strongly recommend speaking with a board-certified genetic counselor before discussing these results with family members.";

export const COUNSELOR_REFERRAL =
  "Find a genetic counselor near you: https://www.nsgc.org/findageneticcounselor";

export function checkSafetyFlags(variants: ExtractedVariant[]): SafetyFlags {
  const highRiskGenes = variants
    .map((v) => v.gene)
    .filter((g) => HIGH_RISK_GENES.has(g));

  return {
    hasHighRiskGenes: highRiskGenes.length > 0,
    highRiskGenes: [...new Set(highRiskGenes)],
    overallConfidence: determineOverallConfidence(variants),
  };
}

function determineOverallConfidence(variants: ExtractedVariant[]): string {
  if (variants.length === 0) return "Uncertain";

  const hasPathogenic = variants.some(
    (v) =>
      v.acmgClassification === "Pathogenic" ||
      v.acmgClassification === "Likely Pathogenic"
  );
  const hasVUS = variants.some((v) =>
    v.acmgClassification.toLowerCase().includes("uncertain")
  );
  const allHaveNotation = variants.every((v) => v.hgvsNotation);

  if (hasPathogenic && allHaveNotation) return "High";
  if (hasVUS || !allHaveNotation) return "Moderate";
  return "High";
}

const PROHIBITED_PATTERNS = [
  /you\s+(?:should|must|need to)\s+(?:start|begin|take|use|try)\s+(?:treatment|medication|therapy|drug)/i,
  /I\s+(?:recommend|suggest|advise)\s+(?:that you|starting|taking)/i,
  /you\s+(?:have|are diagnosed with|suffer from)\s+(?!a variant|a change|a finding)/i,
  /(?:start|begin|take)\s+(?:this|the)\s+(?:medication|drug|treatment)/i,
];

export function scanOutputForProhibitedContent(text: string): string[] {
  const flags: string[] = [];
  for (const pattern of PROHIBITED_PATTERNS) {
    if (pattern.test(text)) {
      flags.push(`Potentially prohibited content detected: ${pattern.source}`);
    }
  }
  return flags;
}
