import type {
  Author,
  ForumSeedThreadInput,
  Reply,
  Thread,
} from "./types";
import { csvRowsToSeedThreads, type QuestionResponseCsvRow } from "./csv-import";
import { normalizeForumTag } from "./format";
import { THREAD_IDEA_SEEDS } from "./thread-ideas.generated";

/**
 * Synthetic seed data so a freshly cloned/started instance has a forum that
 * actually feels alive. These users and threads are clearly marked as sample
 * data (handles end in `~`) so they can never be confused for real members.
 */

export const SEED_USERS: Author[] = [
  { id: "seed-maya", displayName: "Maya", handle: "maya~", role: "parent" },
  { id: "seed-devon", displayName: "Devon", handle: "devon~", role: "teacher" },
  { id: "seed-aarti", displayName: "Aarti", handle: "aarti~", role: "neurodivergent_adult" },
  { id: "seed-ren", displayName: "Ren", handle: "ren~", role: "parent" },
  { id: "seed-sam", displayName: "Sam", handle: "sam~", role: "neurodivergent_adult" },
  { id: "seed-priya", displayName: "Priya", handle: "priya~", role: "teacher" },
  { id: "seed-jordan", displayName: "Jordan", handle: "jordan~", role: "ally" },
  { id: "seed-noor", displayName: "Noor", handle: "noor~", role: "parent" },
  { id: "seed-eli", displayName: "Eli", handle: "eli~", role: "neurodivergent_adult" },
  { id: "seed-leah", displayName: "Leah", handle: "leah~", role: "parent" },
  { id: "seed-kavya", displayName: "Kavya", handle: "kavya~", role: "parent" },
  { id: "seed-tara", displayName: "Tara", handle: "tara~", role: "parent" },
  { id: "seed-nikhil", displayName: "Nikhil", handle: "nikhil~", role: "neurodivergent_adult" },
  { id: "seed-arjun", displayName: "Arjun", handle: "arjun~", role: "neurodivergent_adult" },
  { id: "seed-meera", displayName: "Meera", handle: "meera~", role: "teacher" },
  { id: "seed-rohan", displayName: "Rohan", handle: "rohan~", role: "job_seeker" },
  { id: "seed-divya", displayName: "Divya", handle: "divya~", role: "job_seeker" },
  { id: "seed-csv-workplace", displayName: "Workplace Guide", handle: "workplace-guide~", role: "moderator" },
  { id: "seed-csv-parenting", displayName: "Parenting Guide", handle: "parenting-guide~", role: "moderator" },
  { id: "seed-csv-mental-health", displayName: "Recovery Guide", handle: "recovery-guide~", role: "moderator" },
  { id: "seed-csv-identity", displayName: "Identity Guide", handle: "identity-guide~", role: "moderator" },
  { id: "seed-csv-school", displayName: "School Support Guide", handle: "school-guide~", role: "moderator" },
  { id: "seed-csv-community", displayName: "Community Guide", handle: "community-guide~", role: "moderator" },
];

type Seed = ForumSeedThreadInput;

const QUESTION_RESPONSE_CSV_ROWS: QuestionResponseCsvRow[] = [
  {
    theme: "Workplace and Career Navigation",
    rank: 1,
    question: "How do I explain employment gaps without making my ADHD or burnout sound like a liability?",
    response: "You do not have to narrate every difficult season in detail. A calm version can be: 'I took time for health and skill-building, and I am now ready for a structured role where I can contribute consistently.' Then pivot to proof: projects, courses, freelance work, volunteering, or what you learned about the conditions that help you work well. The goal is not to hide your story. It is to keep the interview focused on your readiness and strengths.",
    suggestedTags: "job-search, employment-gaps, burnout, interview-scripts, adhd",
    anchorThreadType: "Script / Template",
    timeliness: "Evergreen launch seed",
    communityUse: "Anchor discussion and resource page example",
  },
  {
    theme: "Workplace and Career Navigation",
    rank: 2,
    question: "How do I ask my manager for clearer instructions without sounding difficult?",
    response: "Try making it about work quality instead of personal deficiency. For example: 'I do my best work when priorities and next steps are written down. Could we summarize action items after meetings so I can make sure I deliver the right thing?' That is a reasonable work-system request. Many people, ND or not, benefit from written clarity.",
    suggestedTags: "workplace, manager-communication, accommodations, written-briefs",
    anchorThreadType: "What helped me",
    timeliness: "Evergreen launch seed",
    communityUse: "Workplace scripts library",
  },
  {
    theme: "Workplace and Career Navigation",
    rank: 3,
    question: "Is remote work really better for neurodivergent people, or am I just avoiding the office?",
    response: "It can be both: remote work may reduce sensory load and social masking, while the office may offer structure and faster feedback. A useful question is not 'Which one should I be able to tolerate?' but 'Where do I produce good work without paying for it with recovery time?' Some people need remote, some need hybrid, and some need office days with sensory boundaries.",
    suggestedTags: "remote-work, sensory, hybrid-work, workplace-design",
    anchorThreadType: "Open discussion",
    timeliness: "Timely/current workplace topic",
    communityUse: "Forum debate and poll",
  },
  {
    theme: "Workplace and Career Navigation",
    rank: 4,
    question: "How do I stop job-hopping when every role eventually burns me out?",
    response: "Look for the pattern underneath the exits: unclear expectations, sensory overload, too many meetings, no recovery time, or constant masking. Job-hopping is often treated like a character flaw, but it can be useful data. Before the next role, write your non-negotiables, your early warning signs, and the supports you will ask for before you are already depleted.",
    suggestedTags: "career-navigation, burnout, job-hopping, boundaries",
    anchorThreadType: "Open discussion",
    timeliness: "Evergreen launch seed",
    communityUse: "Career planning worksheet",
  },
  {
    theme: "Workplace and Career Navigation",
    rank: 5,
    question: "How do I talk about strengths without sounding like I am overcompensating for my challenges?",
    response: "Use evidence, not hype. Instead of saying 'ADHD is my superpower,' try: 'I am strong at fast pattern recognition and creative problem solving, and I use written systems to manage follow-through.' That keeps the whole picture honest: strengths plus supports. People tend to trust that more than a polished performance.",
    suggestedTags: "strengths, self-advocacy, career-story, job-search",
    anchorThreadType: "What helped me",
    timeliness: "Evergreen launch seed",
    communityUse: "Profile-building prompt",
  },
  {
    theme: "Parenting and Family Systems",
    rank: 1,
    question: "My child just got diagnosed. What should we do first?",
    response: "First, breathe. You do not have to solve the whole future this week. Start with three things: understand the report in plain language, identify the one situation causing the most stress right now, and tell your child in a way that protects their dignity. A diagnosis is not a verdict. It is a map you can slowly learn to use.",
    suggestedTags: "diagnosis, parenting, first-steps, tween-support",
    anchorThreadType: "Start here",
    timeliness: "Evergreen launch seed",
    communityUse: "New parent onboarding resource",
  },
  {
    theme: "Parenting and Family Systems",
    rank: 2,
    question: "How do I help my tween without turning every day into a battle?",
    response: "When everything becomes a battle, the family system is usually overloaded, not lazy or broken. Pick one pressure point: homework, mornings, bedtime, or screens. Change the environment before increasing consequences. Snacks, movement, visual steps, fewer verbal reminders, and a decompression window can do more than another lecture.",
    suggestedTags: "parenting, routines, homework, family-systems",
    anchorThreadType: "What helped me",
    timeliness: "Evergreen launch seed",
    communityUse: "Parent routines guide",
  },
  {
    theme: "Parenting and Family Systems",
    rank: 3,
    question: "How do I explain ADHD or autism to my child without making them feel broken?",
    response: "Use language that separates difference from defect. Something like: 'Your brain works differently, and that means some things are harder and some things may come naturally. Our job is to understand your brain and build supports around it.' Children often remember the emotional tone more than the exact words, so calm and matter-of-fact helps.",
    suggestedTags: "identity, parenting, autism, adhd, self-understanding",
    anchorThreadType: "Script / Template",
    timeliness: "Evergreen launch seed",
    communityUse: "Conversation script page",
  },
  {
    theme: "Parenting and Family Systems",
    rank: 4,
    question: "What do I do when the school says my child is fine, but home tells a different story?",
    response: "Believe the pattern, not just the setting. Many ND children hold it together at school and collapse at home. Document what you see: sleep, meltdowns, avoidance, physical complaints, shutdowns, homework distress. Bring examples, not just conclusions. A child who looks fine all day may still be paying a very high price.",
    suggestedTags: "school-advocacy, masking, parenting, documentation",
    anchorThreadType: "Open discussion",
    timeliness: "Evergreen launch seed",
    communityUse: "Advocacy checklist",
  },
  {
    theme: "Parenting and Family Systems",
    rank: 5,
    question: "How do I take care of myself while advocating for my ND child?",
    response: "Parent advocacy can quietly become a second full-time job. You are allowed to need support too. Start small: one person who can listen without judging, one admin block per week instead of constant firefighting, and one recovery ritual that is not earned by productivity. Your wellbeing is part of the support system, not a bonus.",
    suggestedTags: "parent-wellbeing, advocacy, burnout, family-support",
    anchorThreadType: "Open discussion",
    timeliness: "High emotional relevance",
    communityUse: "Parent wellbeing anchor thread",
  },
  {
    theme: "Mental Health and Recovery",
    rank: 1,
    question: "How do I know if this is burnout and not just me failing again?",
    response: "Burnout often feels personal, but it is usually a signal that demand has exceeded capacity for too long. Look for changes: losing skills you normally have, needing much more recovery, shutdowns, sensory sensitivity, dread, or being unable to start even simple tasks. That is not a moral failure. It is information that your system needs less pressure and more support.",
    suggestedTags: "burnout, recovery, self-compassion, mental-health",
    anchorThreadType: "Open discussion",
    timeliness: "High emotional relevance",
    communityUse: "Burnout recognition resource",
  },
  {
    theme: "Mental Health and Recovery",
    rank: 2,
    question: "What actually helps recovery when rest alone is not fixing it?",
    response: "Rest matters, but recovery often also needs reduced demands, fewer transitions, sensory relief, practical help, and permission to stop performing 'fine.' Think in layers: body basics, environment, workload, relationships, and identity. If you only sleep but return to the same overload, your system may never get a real chance to recover.",
    suggestedTags: "recovery, burnout, sensory, support-systems",
    anchorThreadType: "What helped me",
    timeliness: "Evergreen launch seed",
    communityUse: "Recovery planning guide",
  },
  {
    theme: "Mental Health and Recovery",
    rank: 3,
    question: "My child says scary things when overwhelmed. How seriously should I take it?",
    response: "Take it seriously and calmly. You do not have to panic, but you also do not have to guess alone. Stay close, reduce immediate demands, ask simple direct questions, and contact a qualified professional or local crisis/emergency service if there is any risk of harm. A child saying frightening things is not attention-seeking to dismiss. It is a signal to increase support.",
    suggestedTags: "child-mental-health, crisis-support, parenting, safety",
    anchorThreadType: "Resource",
    timeliness: "Safety-critical evergreen",
    communityUse: "Crisis support signposting page",
  },
  {
    theme: "Mental Health and Recovery",
    rank: 4,
    question: "How do I get out of the shame spiral after a bad ADHD day?",
    response: "Try treating the spiral as a nervous-system event, not a courtroom. First regulate: food, water, movement, quiet, shower, or sleep. Then repair one small thing if needed. The sentence 'I had a hard day, and I can still take the next right step' can be more useful than forcing yourself to feel positive.",
    suggestedTags: "adhd, shame, emotional-regulation, self-compassion",
    anchorThreadType: "What helped me",
    timeliness: "Evergreen launch seed",
    communityUse: "Emotional regulation thread",
  },
  {
    theme: "Mental Health and Recovery",
    rank: 5,
    question: "How do I tell the difference between a meltdown, shutdown, and regular stress?",
    response: "A rough way to think about it: stress says 'this is hard,' meltdown says 'my system has overflowed outward,' and shutdown says 'my system has powered down inward.' The support is often different. During the moment, reduce input and demands. Afterward, look for triggers and recovery needs instead of debating whether the reaction was reasonable.",
    suggestedTags: "meltdown, shutdown, autism, regulation, recovery",
    anchorThreadType: "Resource",
    timeliness: "Evergreen launch seed",
    communityUse: "Psychoeducation explainer",
  },
  {
    theme: "Diagnosis and Identity Navigation",
    rank: 1,
    question: "Why do I feel grief after diagnosis when I thought I would feel relief?",
    response: "Relief and grief can arrive together. Diagnosis can explain your life and also make you mourn the years when you were misunderstood, unsupported, or blamed. That does not mean the diagnosis is bad. It means your story is being rewritten with new information, and that can be tender work.",
    suggestedTags: "diagnosis, grief, late-diagnosis, identity",
    anchorThreadType: "Open discussion",
    timeliness: "Evergreen launch seed",
    communityUse: "Identity anchor discussion",
  },
  {
    theme: "Diagnosis and Identity Navigation",
    rank: 2,
    question: "How do I stop masking without blowing up my whole life?",
    response: "Unmasking does not have to mean becoming unfiltered everywhere overnight. Start with low-risk truth: one sensory preference, one boundary, one honest answer with a safe person. The goal is not to remove every mask immediately. It is to build a life where you need fewer masks to survive.",
    suggestedTags: "masking, unmasking, identity, boundaries",
    anchorThreadType: "Open discussion",
    timeliness: "Evergreen launch seed",
    communityUse: "Identity practice thread",
  },
  {
    theme: "Diagnosis and Identity Navigation",
    rank: 3,
    question: "What if I relate to ADHD or autism content but I do not have a formal diagnosis?",
    response: "You can use helpful strategies without claiming certainty you do not have. It is okay to say, 'I am exploring whether this fits me.' Track patterns over time, read from credible sources and lived experience, and seek assessment if it is accessible and useful. Support needs are real even while labels are still being clarified.",
    suggestedTags: "self-identification, diagnosis, assessment, neurodivergent",
    anchorThreadType: "Start here",
    timeliness: "Timely/current community topic",
    communityUse: "Self-discovery resource page",
  },
  {
    theme: "Diagnosis and Identity Navigation",
    rank: 4,
    question: "How do I tell people about my diagnosis when I am not ready for their reactions?",
    response: "You get to choose the level of disclosure. You might share the practical part first: 'I process verbal instructions better when I can also see them written down.' You do not owe everyone your full diagnostic history. A boundary can be both honest and brief.",
    suggestedTags: "disclosure, diagnosis, boundaries, communication",
    anchorThreadType: "Script / Template",
    timeliness: "Evergreen launch seed",
    communityUse: "Disclosure scripts",
  },
  {
    theme: "Diagnosis and Identity Navigation",
    rank: 5,
    question: "How do I rebuild my self-image after years of thinking I was lazy or broken?",
    response: "Start by changing the explanation, not by demanding instant confidence. Many traits that were called laziness may have been executive function, sensory overload, anxiety, or unsupported difference. Confidence often grows when your life starts fitting your brain better. You are not starting from zero. You are reinterpreting old evidence with a better lens.",
    suggestedTags: "identity, self-compassion, late-diagnosis, reframing",
    anchorThreadType: "Open discussion",
    timeliness: "High emotional relevance",
    communityUse: "Identity recovery anchor thread",
  },
  {
    theme: "School and Learning Support",
    rank: 1,
    question: "What should I put in a one-page profile for my child's teacher?",
    response: "Keep it practical and kind to the teacher's time. Include: what helps my child learn, what can trigger distress, early warning signs, best communication style, sensory needs, and two strengths the teacher should notice. A good profile is not a full history. It is a quick-start guide for helping your child have a better day.",
    suggestedTags: "school, teacher-profile, accommodations, parent-advocacy",
    anchorThreadType: "Template",
    timeliness: "Back-to-school timely seed",
    communityUse: "Downloadable template",
  },
  {
    theme: "School and Learning Support",
    rank: 2,
    question: "How do we handle homework when my child is already exhausted after school?",
    response: "Assume the after-school crash is real. Try a decompression block before homework: food, movement, quiet, no interrogation. Then make the task smaller than feels necessary. Ten calm minutes often beats an hour of conflict. If homework regularly costs the whole evening, it may be time to talk to school about adjustments.",
    suggestedTags: "homework, routines, school, executive-function",
    anchorThreadType: "What helped me",
    timeliness: "Evergreen launch seed",
    communityUse: "Homework support guide",
  },
  {
    theme: "School and Learning Support",
    rank: 3,
    question: "How do I ask school for accommodations without sounding like I am making excuses?",
    response: "Frame accommodations as access to learning, not special treatment. You can say: 'We are trying to reduce barriers so my child can show what they know.' Bring specific examples and specific asks: movement breaks, written instructions, sensory options, chunked assignments, or a check-in point. Specific is harder to dismiss than general worry.",
    suggestedTags: "school-accommodations, advocacy, scripts, learning-support",
    anchorThreadType: "Script / Template",
    timeliness: "Evergreen launch seed",
    communityUse: "School advocacy scripts",
  },
  {
    theme: "School and Learning Support",
    rank: 4,
    question: "What can help with school refusal when pushing harder makes it worse?",
    response: "School refusal is usually communication from an overloaded system. Look for the reason: bullying, sensory overwhelm, anxiety, transitions, academic shame, or masking fatigue. The first goal is not force. It is understanding the barrier well enough to lower it. Work with school on a gradual, supported return rather than a daily power struggle.",
    suggestedTags: "school-refusal, anxiety, sensory, parent-support",
    anchorThreadType: "Open discussion",
    timeliness: "High emotional relevance",
    communityUse: "School refusal resource page",
  },
  {
    theme: "School and Learning Support",
    rank: 5,
    question: "How do we prepare for the move to secondary school without waiting for things to fall apart?",
    response: "Start earlier than feels necessary. Visit with your child's needs in mind, write down likely pressure points, ask how support works in practice, and get agreements in writing. Transitions are easier when the receiving school knows the child before the crisis version of the child appears.",
    suggestedTags: "secondary-transition, school-planning, send, parent-advocacy",
    anchorThreadType: "Resource",
    timeliness: "Seasonal/timely school transition seed",
    communityUse: "Transition checklist",
  },
];

const CSV_SEED_THREADS = csvRowsToSeedThreads(QUESTION_RESPONSE_CSV_ROWS);

export const SEED_THREADS: Seed[] = [
  {
    authorId: "seed-maya",
    spaceId: "first-steps",
    title: "Hi from a tired parent — finally somewhere quiet to talk",
    body: "Just got home from school pickup with a 7yo who had a 30-minute meltdown in the parking lot. Not looking for advice tonight, mostly just wanted to say hi. This place feels softer than the FB groups I've been on.",
    daysAgo: 0,
    tags: ["intro"],
    audienceTags: ["parents"],
    pinned: true,
    reactions: { hug: 18, care: 9, metoo: 12 },
    replies: [
      { authorId: "seed-jordan", body: "Welcome. Take what you need. We're glad you're here.", daysAgo: 0, reactions: { care: 4 } },
      { authorId: "seed-ren", body: "Sending you a hug. Parking lot meltdowns are their own special level of hard.", daysAgo: 0, reactions: { hug: 6, metoo: 3 } },
      { authorId: "seed-noor", body: "You're not alone. There are good days and there are parking-lot days. Tonight just exists.", daysAgo: 0 },
    ],
  },
  {
    authorId: "seed-priya",
    spaceId: "educators",
    title: "Quick reset strategies that don't make a kid feel singled out — what's working?",
    body: "I have a class of 26 and three students who'd benefit from a regulation cue, but I don't want it to be A Thing for them. Currently using a class-wide stretch break every 25 min. What else has worked for you?",
    daysAgo: 1,
    tags: ["classroom", "regulation"],
    audienceTags: ["teachers"],
    reactions: { helpful: 11, thoughtful: 4 },
    replies: [
      { authorId: "seed-devon", body: "We do 'shake it out' — full class stands and shakes one limb at a time. Started as silly, now everyone uses it. The kids who needed it most don't stand out at all.", daysAgo: 1, reactions: { helpful: 9, agree: 3 } },
      { authorId: "seed-jordan", body: "We use color cards on every desk (everyone has them). Quiet way to ask for a check-in without raising a hand.", daysAgo: 1, reactions: { helpful: 7 } },
    ],
  },
  {
    authorId: "seed-aarti",
    spaceId: "adults",
    title: "Asked for accommodations at work today and it went… fine?",
    body: "31 and I finally did the thing. HR was actually kind. I got: noise-canceling headphones reimbursed, an end-of-day 1:1 with my manager instead of a Friday-afternoon team meeting, and explicit permission to skip the open-plan area on heavy days. Posting in case anyone needs proof it can go well.",
    daysAgo: 2,
    tags: ["work", "accommodations", "late-diagnosed"],
    audienceTags: ["nd_adults"],
    reactions: { care: 22, agree: 8, metoo: 14, thanks: 7 },
    replies: [
      { authorId: "seed-sam", body: "This is huge. Saving this thread. Thank you for posting it.", daysAgo: 2, reactions: { thanks: 4 } },
      { authorId: "seed-eli", body: "Did you have a doctor's note or just ask? I'm psyching myself up for a similar conversation.", daysAgo: 2 },
      { authorId: "seed-aarti", body: "Just asked. Said 'I have ADHD and these specific environments make my work day harder' and listed three concrete asks. The specificity helped a lot.", daysAgo: 2, reactions: { helpful: 10 } },
    ],
  },
  {
    authorId: "seed-ren",
    spaceId: "parenting-littles",
    title: "The low-demand morning routine is saving us. Sharing what we changed.",
    body: "We dropped: enforced toothbrushing before breakfast, choosing clothes the night before (he wanted to choose in the morning), and the 'one warning' system. Added: a soft start window of 20 min where nothing has to happen, breakfast at the couch is fine, and a single visual schedule with magnets he moves himself. We've gone from 4 meltdowns/wk to 0–1.",
    daysAgo: 3,
    tags: ["routines", "regulation"],
    audienceTags: ["parents"],
    contentNotes: ["meltdown"],
    reactions: { helpful: 28, thanks: 15, agree: 11 },
    replies: [
      { authorId: "seed-leah", body: "The soft-start window is what unlocked our mornings too. We call it 'wake up time isn't get-up time'.", daysAgo: 3, reactions: { agree: 5 } },
      { authorId: "seed-maya", body: "Trying this tomorrow. Thank you for writing it out so concretely.", daysAgo: 3, reactions: { thanks: 3 } },
      { authorId: "seed-priya", body: "From a teacher: kids who arrive after a soft-start morning are SO much more available to learn. This is upstream work that benefits everyone.", daysAgo: 3, reactions: { helpful: 8 } },
    ],
  },
  {
    authorId: "seed-eli",
    spaceId: "adults",
    title: "Recovering from autistic burnout — what actually helped you?",
    body: "Six months into a hard one. Cut hours, started rest, started OT for sensory stuff. Looking for first-hand experiences of recovery beyond 'it gets better' — what concretely helped your nervous system come back online?",
    daysAgo: 4,
    tags: ["burnout", "recovery"],
    audienceTags: ["nd_adults"],
    contentNotes: ["burnout"],
    reactions: { care: 16, metoo: 19 },
    replies: [
      { authorId: "seed-sam", body: "Permission to be useless was the biggest. Like actually useless, not productive-useless. Year one was rest, year two was rebuilding, year three I'm starting to feel like myself again. There's no fast version.", daysAgo: 4, reactions: { thoughtful: 12, metoo: 8 } },
      { authorId: "seed-aarti", body: "Reduced screens at night, walks daily, no demand-leisure (no 'fun activities I should be doing'). Boring works.", daysAgo: 4 },
    ],
  },
  {
    authorId: "seed-leah",
    spaceId: "tweens-teens",
    title: "12yo just got an autism diagnosis — how do we tell extended family without it becoming A Whole Thing?",
    body: "We're solid. He's solid. The diagnosis gave us a road map. But my MIL is going to ask 30 questions and start sending articles. Looking for scripts that work.",
    daysAgo: 5,
    tags: ["family", "diagnosis"],
    audienceTags: ["parents"],
    contentNotes: ["diagnosis"],
    reactions: { metoo: 7, helpful: 12 },
    replies: [
      { authorId: "seed-noor", body: "What worked for us: 'We have it covered. We'll loop you in on what would be helpful when we know.' Repeat that exact sentence. They eventually stop sending articles.", daysAgo: 5, reactions: { helpful: 14, agree: 6 } },
      { authorId: "seed-ren", body: "Also — your kid gets a vote in who gets told and what. We had our 13yo write the email to the grandparents. Took a lot of pressure off us.", daysAgo: 5, reactions: { thoughtful: 9 } },
    ],
  },
  {
    authorId: "seed-noor",
    spaceId: "healthcare",
    title: "ND-affirming therapist near a major metro — what to actually ask in a consult",
    body: "Looking for a therapist for myself (recently late-diagnosed). I have a list of names but every consult feels like an interview I'll fail. What questions actually surface whether someone is ND-affirming vs. trying to fix you?",
    daysAgo: 6,
    tags: ["therapy", "late-diagnosed"],
    audienceTags: ["nd_adults"],
    reactions: { helpful: 14, thoughtful: 5 },
    replies: [
      { authorId: "seed-jordan", body: "My favorite test question: 'Do you treat masking as a coping skill or as something to work on reducing?' The answer tells you a lot.", daysAgo: 6, reactions: { helpful: 17 } },
      { authorId: "seed-eli", body: "I ask about specific frameworks they use. If they say 'we treat the symptoms', that's a no for me. If they mention neurodiversity-affirming care, polyvagal, internal family systems, I lean in.", daysAgo: 6, reactions: { helpful: 9 } },
    ],
  },
  {
    authorId: "seed-devon",
    spaceId: "educators",
    title: "Sample IEP goal language that's actually measurable — share yours?",
    body: "Compliance officer keeps kicking ours back. Looking for goal templates that pass review without being soulless. Posting one of mine to start.\n\nMine: 'During whole-class instruction, [student] will use a self-identified regulation tool (visual schedule check, fidget, break card) at least 1x per session in 4 of 5 observed periods, as recorded by the case manager.'",
    daysAgo: 7,
    tags: ["iep", "goals", "compliance"],
    audienceTags: ["teachers"],
    reactions: { helpful: 19, thanks: 6 },
    replies: [
      { authorId: "seed-priya", body: "I love the 'self-identified' part. Centers the student's agency and is still measurable.", daysAgo: 7, reactions: { agree: 8 } },
    ],
  },
  {
    authorId: "seed-sam",
    spaceId: "adults",
    title: "Sensory-friendly grocery shopping — current setup",
    body: "Posting in case useful: noise-canceling earbuds, sunglasses indoors (yes, even though it looks weird), a written list in the same order as the store layout, chewable necklace, and a 5-minute decompression in the car after. Cuts a 2-hour ordeal down to 25 minutes flat.",
    daysAgo: 8,
    tags: ["sensory", "daily-life"],
    audienceTags: ["nd_adults"],
    reactions: { helpful: 23, agree: 14, thanks: 8 },
    replies: [
      { authorId: "seed-aarti", body: "The list-in-store-order is a game changer. Mine looks like a treasure map, organized by aisle.", daysAgo: 8, reactions: { agree: 5 } },
    ],
  },
  {
    authorId: "seed-jordan",
    spaceId: "first-steps",
    title: "Welcome — about this space (read first if you're new)",
    body: "We keep this place gentle on purpose. Lead with kindness, use content notes for heavy topics, no diagnosing strangers, identity-first vs. person-first language is a choice. What's shared in support stays in support. If you see something that feels off, flag it — mods get notified within an hour.",
    daysAgo: 14,
    tags: ["meta"],
    pinned: true,
    audienceTags: ["everyone"],
    reactions: { thanks: 41, care: 16 },
  },
  {
    authorId: "seed-maya",
    spaceId: "parenting-littles",
    title: "Sibling support without comparison — looking for scripts",
    body: "5yo neurotypical and 7yo autistic. The 5yo asked tonight, 'why does brother get to leave dinner when he's loud?' Looking for scripts that don't pit them against each other or make special needs sound like a free pass.",
    daysAgo: 9,
    tags: ["siblings"],
    audienceTags: ["parents"],
    reactions: { helpful: 8, metoo: 11 },
    replies: [
      { authorId: "seed-leah", body: "We use 'fair isn't equal — fair is everyone gets what they need.' Then we ask the NT sibling what THEY need. Sometimes it's a quiet snack break, sometimes it's just being heard.", daysAgo: 9, reactions: { helpful: 12, thoughtful: 5 } },
    ],
  },
  {
    authorId: "seed-priya",
    spaceId: "tweens-teens",
    title: "Teen wants to drop their accommodations because 'it makes them weird'. How do you talk about this?",
    body: "Eighth-grader. Has used a fidget, extended time, and a quiet test space for two years. Now wants to opt out of all of it because of a comment a peer made. I don't want to override their voice but I also know they need it.",
    daysAgo: 10,
    tags: ["teens", "advocacy"],
    audienceTags: ["parents"],
    contentNotes: ["school-stress"],
    reactions: { metoo: 8, thoughtful: 14 },
    replies: [
      { authorId: "seed-aarti", body: "From an adult who masked through high school: ask them what they'd choose if no one were watching. Then ask what would make 'being watched' less of a thing — sometimes it's a different cover story for the accommodation, not removing it.", daysAgo: 10, reactions: { thoughtful: 19 } },
    ],
  },
  {
    authorId: "seed-ren",
    spaceId: "healthcare",
    title: "Genetic testing came back with a VUS — what does that mean for our family?",
    body: "Took the panel for our 6yo. One variant came back as 'VUS — variant of unknown significance'. Counselor explained but I'm still fuzzy on what to do with this info.",
    daysAgo: 11,
    tags: ["genetics", "VUS"],
    audienceTags: ["parents"],
    contentNotes: ["medical"],
    reactions: { helpful: 9 },
    replies: [
      { authorId: "seed-jordan", body: "VUS basically means: we found a change in this gene, but we don't yet have enough evidence to call it harmful or harmless. The honest answer is 'wait and revisit in a few years' — variant classifications change as the database grows.", daysAgo: 11, reactions: { helpful: 16, thanks: 4 } },
      { authorId: "seed-jordan", body: "Also — there's a free tool here on SupportNest called GeneTranslate that walks through what a report says in plain language. Worth a look.", daysAgo: 11, reactions: { helpful: 7 } },
    ],
  },
  {
    authorId: "seed-eli",
    spaceId: "first-steps",
    title: "First post — late-diagnosed at 39 and still digesting it",
    body: "Just here to say hi. Got an autism + ADHD diagnosis last month. The relief and grief are showing up at the same time and I don't quite know what to do with that.",
    daysAgo: 12,
    tags: ["intro", "late-diagnosed"],
    audienceTags: ["nd_adults"],
    contentNotes: ["diagnosis"],
    reactions: { care: 24, hug: 18, metoo: 22 },
    replies: [
      { authorId: "seed-aarti", body: "Same exact feeling at 31. The grief is real and you don't have to rush past it. Welcome to the nest.", daysAgo: 12, reactions: { care: 6 } },
      { authorId: "seed-sam", body: "Both feelings are real. Both get to exist at once. Take your time.", daysAgo: 12, reactions: { thoughtful: 4 } },
    ],
  },
  // --- India-context threads adapted from the Moderator Playbook ---
  // SPACE 1: First steps & introductions
  {
    authorId: "seed-kavya",
    spaceId: "first-steps",
    title: "Just got diagnosed — welcome to my chaos, send help (or just hi)",
    body: "Hi from a tired parent (could just as easily be an ND adult). We finished the psych evaluation last week. Part of me feels relieved, part of me feels like I got handed a label when what I needed was actual help.\n\nIf you're here because you just got a diagnosis too — or you're only thinking about it — this is a no-judgment zone. No 'be positive', no 'at least it's not…'. Just space to say out loud what this means for you right now.\n\nDrop a hi if you're new. What just happened in your world that brought you here?",
    daysAgo: 1,
    tags: ["intro", "diagnosis"],
    audienceTags: ["everyone"],
    contentNotes: ["diagnosis"],
    reactions: { hug: 14, care: 8, metoo: 9 },
    replies: [
      { authorId: "seed-csv-community", body: "Welcome — really glad you said hi. That mix of relief and 'where's the actual help' is so common here, and naming it is the first real step. What feels like the most confusing part right now?", daysAgo: 1, reactions: { care: 5 } },
      { authorId: "seed-eli", body: "The label-vs-help feeling hit me hard too. It does start to turn into a map, slowly. Glad you're here.", daysAgo: 1, reactions: { metoo: 4 } },
    ],
  },
  {
    authorId: "seed-tara",
    spaceId: "first-steps",
    title: "Diagnosis doesn't mean I failed — but why does it feel that way?",
    body: "My kid got diagnosed last month. The first thing my mother-in-law said was 'where did we go wrong?' And then my own voice started up: where did I go wrong?\n\nIf you're wrestling with guilt right now — whether it's your diagnosis or your child's — you're not alone, and you're not broken.\n\nThis thread is for naming that guilt without letting it win. What's the story you're telling yourself about what this diagnosis says about you?",
    daysAgo: 2,
    tags: ["guilt", "diagnosis"],
    audienceTags: ["parents"],
    contentNotes: ["diagnosis", "grief"],
    reactions: { hug: 16, care: 11, metoo: 7 },
    replies: [
      { authorId: "seed-csv-community", body: "Thank you for naming this out loud. Notice the evidence in front of us: you're here, you're learning, you showed up the week after a hard diagnosis. That's already a different story than 'I failed.' What would you say to a friend in your exact position?", daysAgo: 2, reactions: { care: 8, thoughtful: 4 } },
      { authorId: "seed-noor", body: "The MIL line nearly broke me too. It got quieter once I stopped trying to win the argument and just said 'this isn't about blame, it's about helping him.'", daysAgo: 2, reactions: { agree: 5 } },
    ],
  },
  {
    authorId: "seed-nikhil",
    spaceId: "first-steps",
    title: "First steps after diagnosis — what actually helped",
    body: "Real talk: the psych handed me a three-page report and sent me on my way. Then I spiraled, Googling for three days straight.\n\nIf you're past that first-week chaos, what's one thing that made it feel less impossible? A resource, a conversation, a single realization that actually landed?\n\nNot toxic positivity. Just real things that helped.",
    daysAgo: 4,
    tags: ["first-steps"],
    audienceTags: ["everyone"],
    contentNotes: ["diagnosis"],
    reactions: { helpful: 13, thanks: 6 },
    replies: [
      { authorId: "seed-csv-community", body: "Love this — let's build a list the next newly-diagnosed person can lean on. To start us off: what's the first thing that helped you stop spiraling, even a little?", daysAgo: 4, reactions: { helpful: 5 } },
      { authorId: "seed-aarti", body: "Closing every tab and finding one community where people talked like humans. That was it for me.", daysAgo: 4, reactions: { agree: 7, thanks: 3 } },
    ],
  },
  // SPACE 2: Parenting little ones (0–8)
  {
    authorId: "seed-kavya",
    spaceId: "parenting-littles",
    title: "Starting school is sensory chaos — and the school calls it a behavior problem",
    body: "My 6yo melts down every single morning before school. Not because she doesn't want to go — it's the transition. Home to uniform to car to a crowded classroom in 20 minutes, and she's fully dysregulated by breakfast.\n\nWe've tried checklists, social stories, all of it. But nobody at school sees it as regulation — they see a behavior problem.\n\nIf your little one struggles with transitions or sensory stuff at school, what's actually helped? And how do you get a school to offer accommodations when they act like you're asking for the moon?",
    daysAgo: 3,
    tags: ["school", "transitions", "sensory"],
    audienceTags: ["parents"],
    contentNotes: ["school-stress", "meltdown"],
    reactions: { metoo: 14, helpful: 9 },
    replies: [
      { authorId: "seed-csv-community", body: "This is such a real one — the morning transition tax is invisible to everyone but you. Pinning this for the practical replies. For folks who've been here: what one change made mornings even slightly softer?", daysAgo: 3, reactions: { care: 6 } },
      { authorId: "seed-ren", body: "Front-loading everything the night before (uniform on the chair, bag packed, shoes by the door) cut our morning demands in half. Fewer decisions before she's even awake.", daysAgo: 3, reactions: { helpful: 11, agree: 4 } },
    ],
  },
  {
    authorId: "seed-tara",
    spaceId: "parenting-littles",
    title: "Early intervention is ₹15,000 a month — how is anyone affording this?",
    body: "Just got quoted ₹15,000/month for speech plus OT. That's half my grocery budget. The psych says early intervention is critical and I believe her — but I also believe in paying rent.\n\nIf you're navigating therapy costs right now, or you found an alternative that actually works, honest question: how are you making it work? Subsidized programs? Government clinics? Things you do at home that genuinely help?\n\nNot judging anyone's choices. Just honesty about what it costs to be a neurodivergent family in India.",
    daysAgo: 5,
    tags: ["therapy-cost", "early-intervention", "india"],
    audienceTags: ["parents"],
    reactions: { metoo: 18, helpful: 7, hug: 9 },
    replies: [
      { authorId: "seed-csv-community", body: "Thank you for saying the quiet part out loud — the cost is real and 'just find cheaper therapy' helps no one. Let's crowdsource honestly: subsidized clinics, NGO programs, district early-intervention centers, anything by city. Where are you based?", daysAgo: 5, reactions: { thanks: 8 } },
      { authorId: "seed-noor", body: "Our district hospital had an OT at a fraction of private rates — long wait, but real. Also a local parent WhatsApp group shares which NGOs run sliding-scale sessions. Ask around more than you'd think to.", daysAgo: 5, reactions: { helpful: 13 } },
    ],
  },
  {
    authorId: "seed-ren",
    spaceId: "parenting-littles",
    title: "Sensory strategies that work for OUR kid (not the generic advice)",
    body: "My son hates the standard fidget toys. He's happiest jumping off the bed or organizing his toys by color for 45 minutes.\n\nI've read a million generic 'sensory diet' posts and they all feel written for some other kid.\n\nWhat sensory input or routine actually works for your child? The weird, specific, doesn't-fit-the-textbook stuff?",
    daysAgo: 7,
    tags: ["sensory", "daily-life"],
    audienceTags: ["parents"],
    reactions: { helpful: 12, agree: 8 },
    replies: [
      { authorId: "seed-csv-community", body: "Yes — 'jumps off the bed for 45 minutes' is way better intel than 'provide proprioceptive input.' Drop your kid's specific weird-that-works thing; specificity is the gift here.", daysAgo: 7, reactions: { helpful: 6 } },
      { authorId: "seed-leah", body: "Mine needs deep pressure she can control — a heavy cushion pile she burrows under after school. We call it the 'reset cave.'", daysAgo: 7, reactions: { helpful: 9, care: 3 } },
    ],
  },
  // SPACE 3: Tweens & teens (9–18)
  {
    authorId: "seed-leah",
    spaceId: "tweens-teens",
    title: "Board exams + neurodivergence — how do we actually do this?",
    body: "My 10th grader is genuinely smart. But board exams are a sensory and executive-function nightmare: three hours of sitting still, silence, time pressure = maximum ADHD. The school says 'no extra time allowed' (there's actually a law for this — they just don't know it).\n\nIf your teen is facing CBSE/ICSE/State boards: are you pushing for accommodations like a scribe, extra time, or separate invigilation? How do you study with their brain instead of against it? And what's your sanity plan for the year?\n\n('Just focus' is not a strategy.)",
    daysAgo: 6,
    tags: ["board-exams", "accommodations", "rpwd", "india"],
    audienceTags: ["parents"],
    contentNotes: ["school-stress", "anxiety"],
    reactions: { metoo: 11, helpful: 15 },
    replies: [
      { authorId: "seed-csv-community", body: "Pinning this — it saves families months of fighting. Quick anchor: under the RPWD Act, candidates with disabilities can request accommodations like extra time and a scribe for board exams; boards have a process even when school staff say 'we've never done it.' For those who've won accommodations: what did the written request look like?", daysAgo: 6, reactions: { helpful: 18, thanks: 6 } },
      { authorId: "seed-priya", body: "Teacher here. Put the request in writing, addressed to the school AND the board, with the diagnostic report attached. 'We've never done it' is not the same as 'it's not allowed.' Document everything.", daysAgo: 6, reactions: { helpful: 12, agree: 5 } },
    ],
  },
  {
    authorId: "seed-leah",
    spaceId: "tweens-teens",
    title: "My teen is lonely (and doesn't know how to fix it)",
    body: "My 13yo is kind, funny, has niche interests — and zero close friends. Not because they're unkind, the opposite. They just miss social cues, don't catch jokes, struggle with the unspoken rules of being a teen.\n\nI watch them sit alone at lunch and it destroys me.\n\nIf your teen has struggled with friendship: is it social skills they need, or just different peers? Have you found clubs or online communities where they actually fit? And how do you support them without making it worse?",
    daysAgo: 8,
    tags: ["friendship", "social-skills"],
    audienceTags: ["parents"],
    contentNotes: ["rejection"],
    reactions: { hug: 13, metoo: 10 },
    replies: [
      { authorId: "seed-csv-community", body: "This one aches — both the parent's helplessness and the teen's isolation are real. Often it's 'different peers' more than 'broken skills.' For folks further along: where did your teen finally find their people?", daysAgo: 8, reactions: { care: 7 } },
      { authorId: "seed-aarti", body: "As the kid who sat alone: interest-based groups saved me, not 'friendship coaching.' A coding club, a D&D table, anything where the activity carries the socializing. Shared focus beats forced small talk.", daysAgo: 8, reactions: { thoughtful: 14, agree: 6 } },
    ],
  },
  {
    authorId: "seed-noor",
    spaceId: "tweens-teens",
    title: "My teen just realized they've been masking for years — now what?",
    body: "My 14yo told me: 'I act normal at school but I'm exhausted.' They didn't use the word masking, but that's exactly it. Years of pretending to focus, sit still, be quiet — and now they're burnt out and don't know who they actually are.\n\nWhere I'm stuck as a parent: do I celebrate that they're finally honest about the exhaustion? Do I help them unmask and risk social fallout at school? How do I support identity-building while they're still inside a rigid system?\n\nIf you've been through this with your teen — or you were that teen — what helped?",
    daysAgo: 9,
    tags: ["masking", "identity", "burnout"],
    audienceTags: ["parents"],
    contentNotes: ["burnout"],
    reactions: { metoo: 12, thoughtful: 11, hug: 7 },
    replies: [
      { authorId: "seed-csv-community", body: "First — that your teen told you this means you're a safe place, which is huge. Masking is real and exhausting, and they have a right to be themselves. What does 'rest from performing' look like for them at home?", daysAgo: 9, reactions: { care: 8 } },
      { authorId: "seed-sam", body: "Unmasked at home first, masked-by-choice at school while it's necessary — that two-speed approach kept me safe AND let me breathe somewhere. They don't have to drop the whole mask everywhere at once.", daysAgo: 9, reactions: { thoughtful: 13, metoo: 5 } },
    ],
  },
  {
    authorId: "seed-kavya",
    spaceId: "tweens-teens",
    title: "My teen thinks they're ADHD — everyone else says she's 'fine'",
    body: "My 16yo daughter is convinced she's ADHD. School says she's fine — good grades, quiet, follows rules. I assumed she was just shy and anxious.\n\nThen I read her diary: exhausted, can't start homework, overthinking every social interaction, sleeping three hours.\n\nWhat if she's right and we're missing it because she masks at school? Girls get missed constantly. If you've fought for a diagnosis when people said 'but she seems fine,' what changed their minds — and how do we actually listen to our teens about their own experience?",
    daysAgo: 11,
    tags: ["gender-bias", "masking", "diagnosis"],
    audienceTags: ["parents"],
    contentNotes: ["diagnosis", "anxiety"],
    reactions: { metoo: 9, helpful: 10 },
    replies: [
      { authorId: "seed-csv-community", body: "Worth naming plainly: girls are routinely missed because they mask and because 'quiet and compliant' hides the struggle. 'Good grades' is not the same as 'okay.' Your daughter's self-knowledge is real data. For those who pushed past 'she seems fine' — what got the assessment moving?", daysAgo: 11, reactions: { agree: 9, helpful: 6 } },
      { authorId: "seed-aarti", body: "Late-diagnosed woman here. The diary is the evidence. We mask hardest where we're watched most. Take her seriously — being believed by a parent is the thing I needed most at 16.", daysAgo: 11, reactions: { care: 7, thoughtful: 5 } },
    ],
  },
  // SPACE 4: Adults — workplace & life
  {
    authorId: "seed-arjun",
    spaceId: "adults",
    title: "Do I tell them about my diagnosis? Navigating work + ADHD/autism",
    body: "Diagnosed at 32. After ten years in corporate, I finally understand why every job felt like drowning.\n\nNow the choice: do I tell my current employer and request accommodations, or keep masking and risk another burnout? People say 'be honest,' but I've also read a hundred stories of people getting fired or passed over after disclosing. In India, disability discrimination is illegal in theory.\n\nIf you've disclosed at work: did you stay at that company? What accommodations actually helped? Was it worth it, or do you regret it?",
    daysAgo: 2,
    tags: ["disclosure", "work", "accommodations"],
    audienceTags: ["nd_adults"],
    contentNotes: ["diagnosis"],
    reactions: { metoo: 15, helpful: 9 },
    replies: [
      { authorId: "seed-csv-community", body: "High-stakes, and there's no single right answer — disclosing and protecting yourself are both valid. One thing that helps: you can often request the change you need ('I do my best work with written briefs') without leading with a diagnosis. For those who disclosed in India — what did you test about the culture first?", daysAgo: 2, reactions: { helpful: 11, thoughtful: 5 } },
      { authorId: "seed-aarti", body: "I disclosed and it went fine — but only after I watched how my manager talked about other people's needs first. Test the culture before you trust it with your label.", daysAgo: 2, reactions: { agree: 8 } },
    ],
  },
  {
    authorId: "seed-nikhil",
    spaceId: "adults",
    title: "Explaining job-hopping without outing myself",
    body: "Six jobs in eight years. Each time burnout hits hard, then I leave. The interviewer sees 'job-hopper, can't commit, red flag.' The reality was undiagnosed ADHD and burnout from masking.\n\nNow that I have a diagnosis I want to reframe it — but 'I had a mental health crisis' feels risky and 'it wasn't right for my brain' sounds weird.\n\nIf you're rebuilding your story after burnout cycles, how are you telling it? And how do you find work that doesn't need eight hours of masking a day?",
    daysAgo: 4,
    tags: ["job-hopping", "burnout", "resume"],
    audienceTags: ["nd_adults"],
    contentNotes: ["burnout"],
    reactions: { metoo: 13, helpful: 8 },
    replies: [
      { authorId: "seed-csv-community", body: "Job-hopping reads as a flaw, but it's often useful data about which conditions deplete you. A calm framing that's landed for people: 'I learned a lot about the environments where I do consistent work, and I'm looking for that fit now.' What's the pattern underneath your exits?", daysAgo: 4, reactions: { helpful: 12, thoughtful: 4 } },
      { authorId: "seed-sam", body: "I stopped apologizing for the gaps and started naming what I learned: I need written priorities and fewer meetings. Saying it as a work-system need, not a confession, changed the whole interview.", daysAgo: 4, reactions: { agree: 7 } },
    ],
  },
  {
    authorId: "seed-aarti",
    spaceId: "adults",
    title: "Building a career around my brain, not against it",
    body: "I keep getting told I should be in tech or data because 'ND people are good at that.' But I hate sitting at a screen eight hours. I thrive on variety, human connection, solving problems in the moment.\n\nSo I'm building something different — freelance consulting. It's terrifying and unstable, but it fits my brain.\n\nIf you've found or built work that aligns with how your brain actually works (not despite it): what's the work, how did you get there, and what's the trade-off — money, stability, freedom?",
    daysAgo: 6,
    tags: ["work", "strengths", "freelance"],
    audienceTags: ["nd_adults"],
    reactions: { helpful: 11, agree: 9, care: 4 },
    replies: [
      { authorId: "seed-csv-community", body: "Love this — there's no single 'ND-friendly job,' only the fit between your wiring and the work. Let's collect a range, not just 'tech is best.' What trade-off did you accept to get the fit you needed?", daysAgo: 6, reactions: { thoughtful: 6 } },
      { authorId: "seed-eli", body: "Went from corporate to a hands-on trade with variety and movement. Less prestige, way less masking, and I stopped dreading Mondays. Worth every rupee I 'lost.'", daysAgo: 6, reactions: { agree: 8, care: 3 } },
    ],
  },
  // SPACE 5: Educators' lounge
  {
    authorId: "seed-meera",
    spaceId: "educators",
    title: "I have a student I don't know how to help",
    body: "I have a 7th grader who can't sit still — constant fidgeting, calling out, interrupting. The parents say ADHD; honestly I've been seeing a discipline problem. I've tried seating changes, behavior charts, detention. Nothing sticks.\n\nHonest question: am I missing something? Is this a neurodivergence thing I need to approach differently? And if so — I have 40 other kids and zero resources. How do I actually do this?\n\nTeachers who've figured this out, help me understand.",
    daysAgo: 3,
    tags: ["classroom", "behavior", "dysregulation"],
    audienceTags: ["teachers"],
    contentNotes: ["school-stress"],
    reactions: { helpful: 14, thanks: 5 },
    replies: [
      { authorId: "seed-csv-community", body: "Thank you for asking instead of writing the kid off — the constraints you're under (40 kids, no support) are real, not excuses. A reframe that helps: a lot of 'won't sit still' is can't-yet-regulate, not won't-behave. Punishment rarely touches dysregulation. What's one low-cost change you could try this week?", daysAgo: 3, reactions: { helpful: 9, thoughtful: 4 } },
      { authorId: "seed-devon", body: "Built-in movement (a class job, handing out papers, a 60-second stretch between tasks) discharges that energy without singling anyone out. Detention adds demand to a kid already over capacity — it backfires every time for mine.", daysAgo: 3, reactions: { helpful: 13, agree: 6 } },
    ],
  },
  {
    authorId: "seed-priya",
    spaceId: "educators",
    title: "Legal accommodations vs. the practical reality of an Indian school",
    body: "A parent asked for separate invigilation and extra time for board exams. I said 'I'll look into it.'\n\nReality: our school has never done this. We don't have the infrastructure, and no one at the board office seems to know the law allows it.\n\nSo do I fight the system for one student? Tell the parent we can't accommodate? Ignore the request? If you're a school leader, teacher, or parent who's navigated this — what's the path forward that doesn't require hiring lawyers?",
    daysAgo: 7,
    tags: ["rpwd", "rte", "accommodations", "india", "legal"],
    audienceTags: ["teachers"],
    contentNotes: ["school-stress"],
    reactions: { helpful: 12, thoughtful: 7 },
    replies: [
      { authorId: "seed-csv-community", body: "Pinning the legal anchor: the RPWD Act (2016) and exam-board guidelines do provide for accommodations like extra time, scribes, and separate rooms — 'we've never done it' isn't the same as 'we can't.' The realistic first step is a written request to the board citing the provision. Has anyone here set this up at a school for the first time?", daysAgo: 7, reactions: { helpful: 15, thanks: 5 } },
      { authorId: "seed-devon", body: "We did it for the first time last year. It was paperwork and persistence, not lawyers — the board had a process buried in their circulars once we asked the right office. Document every email.", daysAgo: 7, reactions: { helpful: 10, agree: 4 } },
    ],
  },
  {
    authorId: "seed-meera",
    spaceId: "educators",
    title: "Small strategies that actually work in a packed classroom",
    body: "Eight years teaching, and after a few ND students I realized: changing my approach changes everything. Small things that work:\n\n- Movement breaks built into the lesson, not as a reward\n- Fidget tools on desks, not treated as contraband\n- Instructions given in writing and spoken\n- Timers for transitions\n- Celebrating effort, not just correctness\n\nNone of this needs a budget — just intention. What's one small thing you do that costs nothing but makes a huge difference?",
    daysAgo: 10,
    tags: ["classroom", "low-resource"],
    audienceTags: ["teachers"],
    reactions: { helpful: 17, thanks: 8, agree: 6 },
    replies: [
      { authorId: "seed-csv-community", body: "This is gold — and the best part is ND-friendly is just better-for-everyone teaching. Let's build the no-budget list together. What's your one zero-cost move?", daysAgo: 10, reactions: { helpful: 7 } },
      { authorId: "seed-priya", body: "Visual agenda on the board every day, ticked off as we go. Costs nothing, and the whole class settles when they can see the shape of the lesson.", daysAgo: 10, reactions: { helpful: 11, agree: 5 } },
    ],
  },
  // SPACE 6: Healthcare & genetics
  {
    authorId: "seed-noor",
    spaceId: "healthcare",
    title: "How do you find a psych who actually gets it? (India)",
    body: "I've called eight doctors. One said ADHD doesn't exist in girls. One wanted to medicate immediately. One told me to just 'parent better.' I'm exhausted and we're no closer to a diagnosis.\n\nIf you've found a good clinician — one who listens, doesn't pathologize, knows current diagnostic criteria — help a parent out: how did you find them? What should I ask to vet someone before booking? Red flags? And rough cost in your city?\n\n(Please include your city/region so others can use your recs.)",
    daysAgo: 5,
    tags: ["clinician", "diagnosis", "india"],
    audienceTags: ["everyone"],
    contentNotes: ["medical", "diagnosis"],
    reactions: { helpful: 13, metoo: 8 },
    replies: [
      { authorId: "seed-csv-community", body: "Eight calls like that is genuinely demoralizing — I'm sorry. Let's build a city-by-city list of clinicians who do this well. A good assessment usually means: full history, more than a 15-minute chat, talks about strengths and challenges, and doesn't rush to a single label. What city are you in?", daysAgo: 5, reactions: { thanks: 7, care: 5 } },
      { authorId: "seed-jordan", body: "Vetting question that saved me: 'How do you assess in girls and women specifically?' A blank pause is your answer. Good ones light up and talk about masking.", daysAgo: 5, reactions: { helpful: 12 } },
    ],
  },
  {
    authorId: "seed-kavya",
    spaceId: "healthcare",
    title: "The clinician recommended medication and I'm terrified",
    body: "The doctor says ADHD medication could help with focus and regulation. But my mom says it's addictive, a Facebook group says it's overprescribed to control kids, and a Reddit thread says it ruined someone's life.\n\nI trust the clinician's judgment. I'm also terrified of getting this wrong.\n\nIf you've gone the medication route — for yourself or your child — what was your actual experience? Not scaremongering, not toxic positivity. Just real. What should I know before we start?",
    daysAgo: 8,
    tags: ["medication", "india"],
    audienceTags: ["parents"],
    contentNotes: ["medical"],
    reactions: { metoo: 10, helpful: 9, hug: 5 },
    replies: [
      { authorId: "seed-csv-community", body: "Totally fair to be scared — and the noise online makes it worse. Medication is one tool among several, started low and monitored, not a permanent verdict. We can share real experiences here, but the dosing conversation belongs with your prescriber. For those who tried it: what surprised you, good or bad?", daysAgo: 8, reactions: { helpful: 11, thanks: 4 } },
      { authorId: "seed-eli", body: "For me it wasn't a personality change, just turning the background noise down a notch. We started tiny and adjusted. The scary stories online were nothing like my actual experience — but it's individual, so go slow with your doctor.", daysAgo: 8, reactions: { helpful: 9, care: 3 } },
    ],
  },
  {
    authorId: "seed-arjun",
    spaceId: "healthcare",
    title: "My kid's diagnosis, and suddenly 'oh… that's me too'",
    body: "My kid got diagnosed. Now I'm reading about ADHD in adults and going 'oh.' My whole childhood makes sense — the job struggles, the relationships, the organization chaos. It all clicks.\n\nThe parent group says 'you're not alone, lots of parents discover they're ND too.' But I also don't want to armchair-diagnose myself.\n\nIf you've gone down this road (kid's diagnosis → realizing you might be ND too): what helped? Did you seek your own assessment? Did it change how you show up for your kid's journey?",
    daysAgo: 12,
    tags: ["genetics", "late-diagnosis"],
    audienceTags: ["everyone"],
    contentNotes: ["medical", "diagnosis"],
    reactions: { metoo: 14, care: 7 },
    replies: [
      { authorId: "seed-csv-community", body: "This 'oh' moment is one of the most common stories in this whole community. Recognizing yourself in your kid's diagnosis isn't self-pathologizing — it's new information about an old story. Did understanding yourself change how you parent the journey?", daysAgo: 12, reactions: { thoughtful: 8, care: 5 } },
      { authorId: "seed-aarti", body: "Getting my own assessment after my nephew's changed everything — I stopped parenting from shame and started from understanding. Even if you never get a formal label, the self-compassion alone is worth it.", daysAgo: 12, reactions: { care: 9, agree: 4 } },
    ],
  },
  // SPACE 7: Job seekers
  {
    authorId: "seed-rohan",
    spaceId: "job seekers",
    title: "Resume gaps that don't sound like excuses",
    body: "I had a breakdown at my last job and left. Now I'm back on the market. The honest version is 'that role wasn't sustainable for my mental health.' The scary version is what the interviewer hears: 'unstable, will quit again.'\n\nI'm rebuilding my resume and my story, but I don't want to lie, over-share my mental health, or sound like a liability.\n\nHow have you handled employment gaps in India's job market? What version of your story actually landed you an interview?",
    daysAgo: 3,
    tags: ["resume-gaps", "interview"],
    audienceTags: ["job_seekers"],
    contentNotes: ["unemployment", "burnout"],
    reactions: { metoo: 12, helpful: 8 },
    replies: [
      { authorId: "seed-csv-community", body: "Gaps are so common and so survivable — burnout is real, not a character flaw. A framing people have landed interviews with: 'I took intentional time to reset and build skills, and I'm ready for a structured role.' Then pivot fast to proof. What were you doing during the gap that we can frame as growth?", daysAgo: 3, reactions: { helpful: 13, thanks: 5 } },
      { authorId: "seed-divya", body: "I named the gap in one calm sentence and moved straight to a project I'd built. Interviewers followed my lead — when I didn't treat it as shameful, neither did they.", daysAgo: 3, reactions: { agree: 7 } },
    ],
  },
  {
    authorId: "seed-divya",
    spaceId: "job seekers",
    title: "Actually getting through interviews when your brain works differently",
    body: "I'm great at my job and terrible at selling myself in an interview. I blank on pre-rehearsed stories, get overwhelmed by group assessments, and fixate on one hard question while losing the thread of everything else.\n\nNeurodivergent-friendly interview strategies would be amazing. Also — companies like Atypical Advantage and Nagarro run neuro-affirming hiring. Has anyone applied there, and what was different?\n\nWhat's one interview hack that's actually worked for you?",
    daysAgo: 6,
    tags: ["interview", "atypical-advantage"],
    audienceTags: ["job_seekers"],
    contentNotes: ["anxiety"],
    reactions: { helpful: 11, metoo: 9 },
    replies: [
      { authorId: "seed-csv-community", body: "Interview anxiety is not a measure of how good you'd be at the job. Practical hacks welcome here — and yes, neuro-affirming hiring (Atypical Advantage, Nagarro's TestingPro, some EY/SAP tracks) genuinely runs differently: clearer expectations, less performance-under-pressure. What's the one thing that trips you up most so we can troubleshoot it?", daysAgo: 6, reactions: { helpful: 10, thanks: 4 } },
      { authorId: "seed-arjun", body: "Asking to see questions in writing, or for a second to jot a keyword before answering, stopped me blanking. Good interviewers don't blink at it. The neuro-affirming processes I tried actually offered it upfront.", daysAgo: 6, reactions: { helpful: 9, agree: 5 } },
    ],
  },
  {
    authorId: "seed-rohan",
    spaceId: "job seekers",
    title: "What actually makes a role (or company) neurodivergent-friendly?",
    body: "After five jobs where I burnt out, I finally found one that works. Not because it's easy — it's not. But:\n\n- Flexible deadlines (not everything is urgent)\n- Async is normal (I don't have to perform focus eight hours a day)\n- A manager who gets it (judges results, not how I work)\n- Remote option (no sensory-overload commute)\n- Real mental-health days, not frowned upon\n\nIt's rare, but it exists. What's made a role actually sustainable for you? What's non-negotiable?",
    daysAgo: 9,
    tags: ["workplace", "remote", "accommodations"],
    audienceTags: ["job_seekers"],
    reactions: { helpful: 14, agree: 10, thanks: 5 },
    replies: [
      { authorId: "seed-csv-community", body: "This is the hopeful one — proof that sustainable roles exist. Let's name the green flags so the next person can look for them in a job description. What's your single non-negotiable?", daysAgo: 9, reactions: { thanks: 6 } },
      { authorId: "seed-nikhil", body: "Async plus 'results not hours' is my non-negotiable now. The day a manager said 'I don't care when you do it, just keep me posted,' my whole nervous system unclenched.", daysAgo: 9, reactions: { agree: 8, care: 3 } },
    ],
  },
  ...CSV_SEED_THREADS,
  ...THREAD_IDEA_SEEDS,
];

export function buildSeedReplies(): {
  threads: Thread[];
  replies: Reply[];
} {
  const now = Date.now();
  const day = 24 * 60 * 60 * 1000;
  const threads: Thread[] = [];
  const replies: Reply[] = [];

  for (let i = 0; i < SEED_THREADS.length; i++) {
    const s = SEED_THREADS[i];
    const tid =
      s.seedId ??
      (s.seedMetadata
        ? `seed-csv-${normalizeForumTag(s.seedMetadata.theme)}-${s.seedMetadata.rank}`
        : `seed-thread-${i + 1}`);
    const created = new Date(
      now - s.daysAgo * day + (s.minutesOffset ?? 0) * 60_000
    ).toISOString();
    const tReactions = Object.entries(s.reactions ?? {}).flatMap(
      ([emoji, count]) =>
        Array.from({ length: count ?? 0 }).map((_, k) => ({
          userId: `seed-reactor-t${i}-${emoji}-${k}`,
          emoji: emoji as never,
        }))
    );

    const t: Thread = {
      id: tid,
      spaceId: s.spaceId,
      authorId: s.authorId,
      title: s.title,
      body: s.body,
      createdAt: created,
      updatedAt: created,
      lastActivityAt: created,
      tags: s.tags ?? [],
      audienceTags: s.audienceTags ?? ["everyone"],
      contentNotes: s.contentNotes ?? [],
      isPinned: !!s.pinned,
      isLocked: false,
      viewCount: 50 + i * 13,
      reactions: tReactions,
      seedMetadata: s.seedMetadata,
    };

    let lastActivity = created;
    (s.replies ?? []).forEach((r, j) => {
      const rid = `seed-reply-${i + 1}-${j + 1}`;
      const rCreated = new Date(
        now -
          r.daysAgo * day +
          ((r.minutesOffset ?? 0) + j + 1) * 60_000
      ).toISOString();
      const rReactions = Object.entries(r.reactions ?? {}).flatMap(
        ([emoji, count]) =>
          Array.from({ length: count ?? 0 }).map((_, k) => ({
            userId: `seed-reactor-r${i}-${j}-${emoji}-${k}`,
            emoji: emoji as never,
          }))
      );
      replies.push({
        id: rid,
        threadId: tid,
        authorId: r.authorId,
        body: r.body,
        createdAt: rCreated,
        reactions: rReactions,
      });
      if (rCreated > lastActivity) lastActivity = rCreated;
    });
    t.lastActivityAt = lastActivity;
    threads.push(t);
  }

  return { threads, replies };
}
